CREATE DATABASE IF NOT EXISTS BD_FLIX;

CREATE USER 'BD_FLIX'@'localhost' IDENTIFIED BY 'BD_FLIX_SQL';

GRANT CREATE ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT ALTER ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT CREATE VIEW ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT DELETE ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT DROP ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT INDEX ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT INSERT ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT REFERENCES ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT SELECT ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT SHOW VIEW ON BD_FLIX.* TO 'BD_FLIX'@'localhost';
GRANT UPDATE ON BD_FLIX.* TO 'BD_FLIX'@'localhost';